# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/designer/mainwindow_v4.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(830, 569))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QWidget#centralwidget { border-image: url(:/icons/src/user interface/autobot-ui-background.png); }")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.topbar = QtWidgets.QHBoxLayout()
        self.topbar.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.topbar.setContentsMargins(-1, -1, -1, 5)
        self.topbar.setSpacing(11)
        self.topbar.setObjectName("topbar")
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topbar.addItem(spacerItem1)
        self.save_menu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_menu.sizePolicy().hasHeightForWidth())
        self.save_menu.setSizePolicy(sizePolicy)
        self.save_menu.setText("")
        self.save_menu.setPixmap(QtGui.QPixmap(":/icons/src/icons/save-icon.png"))
        self.save_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.save_menu.setObjectName("save_menu")
        self.topbar.addWidget(self.save_menu)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topbar.addItem(spacerItem2)
        self.open_menu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_menu.sizePolicy().hasHeightForWidth())
        self.open_menu.setSizePolicy(sizePolicy)
        self.open_menu.setText("")
        self.open_menu.setPixmap(QtGui.QPixmap(":/icons/src/icons/open-icon.png"))
        self.open_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.open_menu.setObjectName("open_menu")
        self.topbar.addWidget(self.open_menu)
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topbar.addItem(spacerItem3)
        self.reports_menu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reports_menu.sizePolicy().hasHeightForWidth())
        self.reports_menu.setSizePolicy(sizePolicy)
        self.reports_menu.setText("")
        self.reports_menu.setPixmap(QtGui.QPixmap(":/icons/src/icons/reports-icon.png"))
        self.reports_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.reports_menu.setObjectName("reports_menu")
        self.topbar.addWidget(self.reports_menu)
        spacerItem4 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topbar.addItem(spacerItem4)
        self.login_menu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_menu.sizePolicy().hasHeightForWidth())
        self.login_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.login_menu.setFont(font)
        self.login_menu.setStyleSheet("QLabel#login_menu { color: rgb(54, 122, 255);}")
        self.login_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.login_menu.setObjectName("login_menu")
        self.topbar.addWidget(self.login_menu)
        spacerItem5 = QtWidgets.QSpacerItem(275, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topbar.addItem(spacerItem5)
        self.quit_menu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_menu.sizePolicy().hasHeightForWidth())
        self.quit_menu.setSizePolicy(sizePolicy)
        self.quit_menu.setText("")
        self.quit_menu.setPixmap(QtGui.QPixmap(":/icons/src/icons/quit-icon.png"))
        self.quit_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.quit_menu.setObjectName("quit_menu")
        self.topbar.addWidget(self.quit_menu)
        spacerItem6 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topbar.addItem(spacerItem6)
        self.gridLayout.addLayout(self.topbar, 0, 1, 1, 2)
        self.sidemenu = QtWidgets.QVBoxLayout()
        self.sidemenu.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.sidemenu.setContentsMargins(5, 40, -1, -1)
        self.sidemenu.setObjectName("sidemenu")
        self.ui_icon = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_icon.sizePolicy().hasHeightForWidth())
        self.ui_icon.setSizePolicy(sizePolicy)
        self.ui_icon.setMaximumSize(QtCore.QSize(65, 65))
        self.ui_icon.setStyleSheet("")
        self.ui_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(':/icons/src/icons/ui-icon.png'))
        icon.addPixmap(QtGui.QPixmap(':/icons/src/icons/ui-icon-active.png'), QtGui.QIcon.Active)
        self.ui_icon.setIcon(icon)
        self.ui_icon.setIconSize(QtCore.QSize(65, 65))
        self.ui_icon.setFlat(True)
        self.ui_icon.setObjectName("ui_icon")
        self.sidemenu.addWidget(self.ui_icon)
        self.dhcp_icon = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dhcp_icon.sizePolicy().hasHeightForWidth())
        self.dhcp_icon.setSizePolicy(sizePolicy)
        self.dhcp_icon.setMaximumSize(QtCore.QSize(65, 65))
        self.dhcp_icon.setStyleSheet("")
        self.dhcp_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(':/icons/src/icons/dhcp-icon.png'))
        icon1.addPixmap(QtGui.QPixmap(':/icons/src/icons/dhcp-icon-active.png'), QtGui.QIcon.Active)
        self.dhcp_icon.setIcon(icon1)
        self.dhcp_icon.setIconSize(QtCore.QSize(65, 65))
        self.dhcp_icon.setFlat(True)
        self.dhcp_icon.setObjectName("dhcp_icon")
        self.sidemenu.addWidget(self.dhcp_icon)
        self.wifi24_icon = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifi24_icon.sizePolicy().hasHeightForWidth())
        self.wifi24_icon.setSizePolicy(sizePolicy)
        self.wifi24_icon.setMaximumSize(QtCore.QSize(65, 65))
        self.wifi24_icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(':/icons/src/icons/wifi-2.4-icon.png'))
        icon2.addPixmap(QtGui.QPixmap(':/icons/src/icons/wifi-2.4-icon-active.png'), QtGui.QIcon.Active)
        self.wifi24_icon.setIcon(icon2)
        self.wifi24_icon.setIconSize(QtCore.QSize(65, 65))
        self.wifi24_icon.setFlat(True)
        self.wifi24_icon.setObjectName("wifi24_icon")
        self.sidemenu.addWidget(self.wifi24_icon)
        self.wifi5_icon = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifi5_icon.sizePolicy().hasHeightForWidth())
        self.wifi5_icon.setSizePolicy(sizePolicy)
        self.wifi5_icon.setMaximumSize(QtCore.QSize(65, 65))
        self.wifi5_icon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(':/icons/src/icons/wifi-5.0-icon.png'))
        icon3.addPixmap(QtGui.QPixmap(':/icons/src/icons/wifi-5.0-active.png'), QtGui.QIcon.Active)
        self.wifi5_icon.setIcon(icon3)
        self.wifi5_icon.setIconSize(QtCore.QSize(65, 65))
        self.wifi5_icon.setFlat(True)
        self.wifi5_icon.setObjectName("wifi5_icon")
        self.sidemenu.addWidget(self.wifi5_icon)
        self.ipv6_icon = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipv6_icon.sizePolicy().hasHeightForWidth())
        self.ipv6_icon.setSizePolicy(sizePolicy)
        self.ipv6_icon.setMaximumSize(QtCore.QSize(65, 65))
        self.ipv6_icon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(':/icons/src/icons/ipv6-icon.png'))
        icon4.addPixmap(QtGui.QPixmap(':/icons/src/icons/ipv6-icon-active.png'), QtGui.QIcon.Active)
        self.ipv6_icon.setIcon(icon4)
        self.ipv6_icon.setIconSize(QtCore.QSize(65, 65))
        self.ipv6_icon.setFlat(True)
        self.ipv6_icon.setObjectName("ipv6_icon")
        self.sidemenu.addWidget(self.ipv6_icon)
        spacerItem7 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.sidemenu.addItem(spacerItem7)
        self.gridLayout.addLayout(self.sidemenu, 1, 0, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(458, 650, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem8, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        self.app_version = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.app_version.setFont(font)
        self.app_version.setStyleSheet("QLabel#app_version {color: rgb(85, 85, 85);}")
        self.app_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.app_version.setObjectName("app_version")
        self.gridLayout.addWidget(self.app_version, 2, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 3, 1, 1)
        self.app_version.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_menu.setText(_translate("MainWindow", "NET3P (DMC7001KNB)"))
        self.app_version.setText(_translate("MainWindow", "Autobot v5.0"))

import autobot.ui.resources_rc
