# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/designer/login.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.setWindowModality(QtCore.Qt.ApplicationModal)
        LoginForm.resize(440, 700)
        LoginForm.setFocusPolicy(QtCore.Qt.StrongFocus)
        LoginForm.setStyleSheet("QWidget#LoginForm { background-color: rgb(255, 255, 255); }")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout_7.setContentsMargins(30, 19, 30, 19)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.logo_icon = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_icon.sizePolicy().hasHeightForWidth())
        self.logo_icon.setSizePolicy(sizePolicy)
        self.logo_icon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo_icon.setText("")
        self.logo_icon.setPixmap(QtGui.QPixmap(":/fonts/src/autbot-id-login.png"))
        self.logo_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_icon.setObjectName("logo_icon")
        self.horizontalLayout_2.addWidget(self.logo_icon)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.logo_label = QtWidgets.QLabel(LoginForm)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.logo_label.setFont(font)
        self.logo_label.setStyleSheet("QLabel#logo_label {color: rgb(112, 112, 112);}")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_7.addWidget(self.logo_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usrLabel = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usrLabel.sizePolicy().hasHeightForWidth())
        self.usrLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.usrLabel.setFont(font)
        self.usrLabel.setStyleSheet("QLabel#usrLabel {color: rgb(112, 112, 112);}")
        self.usrLabel.setObjectName("usrLabel")
        self.verticalLayout.addWidget(self.usrLabel)
        self.usrText = QtWidgets.QLineEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usrText.sizePolicy().hasHeightForWidth())
        self.usrText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.usrText.setFont(font)
        self.usrText.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.usrText.setAutoFillBackground(False)
        self.usrText.setStyleSheet("QLineEdit#usrText {color: rgb(112, 112, 112);}")
        self.usrText.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.usrText.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.usrText.setClearButtonEnabled(False)
        self.usrText.setObjectName("usrText")
        self.verticalLayout.addWidget(self.usrText)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pwd_label = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwd_label.sizePolicy().hasHeightForWidth())
        self.pwd_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.pwd_label.setFont(font)
        self.pwd_label.setStyleSheet("QLabel#pwd_label {color: rgb(112, 112, 112);}")
        self.pwd_label.setObjectName("pwd_label")
        self.verticalLayout_2.addWidget(self.pwd_label)
        self.pwd_text = QtWidgets.QLineEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwd_text.sizePolicy().hasHeightForWidth())
        self.pwd_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.pwd_text.setFont(font)
        self.pwd_text.setStyleSheet("QLineEdit#pwd_text {color: rgb(112, 112, 112);}")
        self.pwd_text.setObjectName("pwd_text")
        self.verticalLayout_2.addWidget(self.pwd_text)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ssid24Label = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssid24Label.sizePolicy().hasHeightForWidth())
        self.ssid24Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.ssid24Label.setFont(font)
        self.ssid24Label.setStyleSheet("QLabel#ssid24Label {color: rgb(112, 112, 112);}")
        self.ssid24Label.setObjectName("ssid24Label")
        self.verticalLayout_4.addWidget(self.ssid24Label)
        self.ssid24Text = QtWidgets.QLineEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssid24Text.sizePolicy().hasHeightForWidth())
        self.ssid24Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.ssid24Text.setFont(font)
        self.ssid24Text.setStyleSheet("QLineEdit#ssid24Text {color: rgb(112, 112, 112);}")
        self.ssid24Text.setObjectName("ssid24Text")
        self.verticalLayout_4.addWidget(self.ssid24Text)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pass24Label = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass24Label.sizePolicy().hasHeightForWidth())
        self.pass24Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.pass24Label.setFont(font)
        self.pass24Label.setStyleSheet("QLabel#pass24Label {color: rgb(112, 112, 112);}")
        self.pass24Label.setObjectName("pass24Label")
        self.verticalLayout_3.addWidget(self.pass24Label)
        self.pass24Text = QtWidgets.QLineEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass24Text.sizePolicy().hasHeightForWidth())
        self.pass24Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.pass24Text.setFont(font)
        self.pass24Text.setStyleSheet("QLineEdit#pass24Text {color: rgb(112, 112, 112);}")
        self.pass24Text.setObjectName("pass24Text")
        self.verticalLayout_3.addWidget(self.pass24Text)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ssid5Label = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssid5Label.sizePolicy().hasHeightForWidth())
        self.ssid5Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.ssid5Label.setFont(font)
        self.ssid5Label.setStyleSheet("QLabel#ssid5Label {color: rgb(112, 112, 112);}")
        self.ssid5Label.setObjectName("ssid5Label")
        self.verticalLayout_5.addWidget(self.ssid5Label)
        self.ssid5Text = QtWidgets.QLineEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssid5Text.sizePolicy().hasHeightForWidth())
        self.ssid5Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.ssid5Text.setFont(font)
        self.ssid5Text.setStyleSheet("QLineEdit#ssid5Text {color: rgb(112, 112, 112);}")
        self.ssid5Text.setObjectName("ssid5Text")
        self.verticalLayout_5.addWidget(self.ssid5Text)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pass5Label = QtWidgets.QLabel(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass5Label.sizePolicy().hasHeightForWidth())
        self.pass5Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.pass5Label.setFont(font)
        self.pass5Label.setStyleSheet("QLabel#pass5Label {color: rgb(112, 112, 112);}")
        self.pass5Label.setObjectName("pass5Label")
        self.verticalLayout_6.addWidget(self.pass5Label)
        self.pass5Text = QtWidgets.QLineEdit(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass5Text.sizePolicy().hasHeightForWidth())
        self.pass5Text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.pass5Text.setFont(font)
        self.pass5Text.setStyleSheet("QLineEdit#pass5Text {color: rgb(112, 112, 112);}")
        self.pass5Text.setObjectName("pass5Text")
        self.verticalLayout_6.addWidget(self.pass5Text)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem8)
        self.login_btn = QtWidgets.QPushButton(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMaximumSize(QtCore.QSize(400, 46))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton#login_btn { border: None; background-color: rgb(0, 104, 255);  color: rgb(255, 255, 255);}")
        self.login_btn.setFlat(False)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_7.addWidget(self.login_btn)
        self.login_btn.raise_()
        self.logo_label.raise_()

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.logo_label.setText(_translate("LoginForm", "Log in with Web UI info and run your tests!"))
        self.usrLabel.setText(_translate("LoginForm", "Username"))
        self.pwd_label.setText(_translate("LoginForm", "Password"))
        self.ssid24Label.setText(_translate("LoginForm", "SSID 2.4Ghz"))
        self.pass24Label.setText(_translate("LoginForm", "SSID 2.4Ghz Password"))
        self.ssid5Label.setText(_translate("LoginForm", "SSID 5.0 Ghz"))
        self.pass5Label.setText(_translate("LoginForm", "SSID 5.0Ghz Password"))
        self.login_btn.setText(_translate("LoginForm", "Login"))

import autobot.ui.resources_rc
